package pojos;
// Generated 13-ene-2019 11:51:36 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Asistenciamedica generated by hbm2java
 */
public class Asistenciamedica  implements java.io.Serializable {


     private Integer idAsistenciaMedica;
     private Integer idSeguro;
     private String breveDescripcion;
     private String lugar;
     private String explicacion;
     private String tipoAsistencia;
     private Date fecha;
     private Date hora;
     private BigDecimal importe;
     private Integer idx;

    public Asistenciamedica() {
    }

    public Asistenciamedica(Integer idSeguro, String breveDescripcion, String lugar, String explicacion, String tipoAsistencia, Date fecha, Date hora, BigDecimal importe, Integer idx) {
       this.idSeguro = idSeguro;
       this.breveDescripcion = breveDescripcion;
       this.lugar = lugar;
       this.explicacion = explicacion;
       this.tipoAsistencia = tipoAsistencia;
       this.fecha = fecha;
       this.hora = hora;
       this.importe = importe;
       this.idx = idx;
    }
   
    public Integer getIdAsistenciaMedica() {
        return this.idAsistenciaMedica;
    }
    
    public void setIdAsistenciaMedica(Integer idAsistenciaMedica) {
        this.idAsistenciaMedica = idAsistenciaMedica;
    }
    public Integer getIdSeguro() {
        return this.idSeguro;
    }
    
    public void setIdSeguro(Integer idSeguro) {
        this.idSeguro = idSeguro;
    }
    public String getBreveDescripcion() {
        return this.breveDescripcion;
    }
    
    public void setBreveDescripcion(String breveDescripcion) {
        this.breveDescripcion = breveDescripcion;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public String getExplicacion() {
        return this.explicacion;
    }
    
    public void setExplicacion(String explicacion) {
        this.explicacion = explicacion;
    }
    public String getTipoAsistencia() {
        return this.tipoAsistencia;
    }
    
    public void setTipoAsistencia(String tipoAsistencia) {
        this.tipoAsistencia = tipoAsistencia;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public BigDecimal getImporte() {
        return this.importe;
    }
    
    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }
    public Integer getIdx() {
        return this.idx;
    }
    
    public void setIdx(Integer idx) {
        this.idx = idx;
    }




}


